### ISSUE TITLE
Remix not loading with Star Wars Republic Commando, even with d3d8to9

### ISSUE THREAD

**Issue by rpw4646** [NVIDIAGameWorks/rtx-remix#41]
**Description**
Republic Commando launches fine, but RTX remix does not load. 
There are no logs created in the game directory.
Attempted to load using d3d9.dll alone, both the d3d9.dll and d3d8.dll together, and the d3d8.dll alone

**To Reproduce**
Simply attempt to launch Republic Commando with the remix files + the d3d8to9 d3d8.dll

**Expected behavior**
RTX remix should load in

**Comment by ThatD07** [comment]
I fixed it by launching the game without RTX Remix and changing the resolution to 1600x1200

**Comment by rpw4646** [comment]
Still not loading for me after a fresh install, I wonder if its worth trying the disk version. Are there any other settings you changed before restarting and adding Remix?

**Comment by ThatD07** [comment]
Not really no, I used the same d3d8tod9 wrapper as well and got ingame after changing the res
![Star Wars Republic Commando 2023  04  14  12_54_23](https://user-images.githubusercontent.com/26389402/232025924-2e351985-1a55-4aae-b66d-be18089a68bb.png)
![Star Wars Republic Commando 2023  04  14  12_53_04](https://user-images.githubusercontent.com/26389402/232025932-77019078-ae78-4c74-ab89-65119ffeaba6.png)
![Uploading Star Wars Republic Commando 2023. 04. 14. 12_53_56.png…]()

I have the Steam version btw

**Comment by sb1138** [comment]
I had this issue on the steam version, ensure that rtx remix is in the system folder with the game.exe not the main folder with the shortcut.exe.

**Comment by rpw4646** [comment]
> 

Yep, that's what I was doing wrong. Works perfectly now.
