### ISSUE TITLE
Fallout New Vegas has abnormally poor performance

### ISSUE THREAD

**Issue by Kim2091** [NVIDIAGameWorks/rtx-remix#423]
**Describe the bug**
- Once configured, Fallout New Vegas has abnormally poor performance compared to other games. On an i7 12700k and RTX 4090, I'm only getting 17-18 FPS. The DXVK hud reports 100% GPU utilization, but in actuality it's closer to 30%.
- dxvk-remix-b5d9a25-430-debugoptimized
- bridge-remix-667869b-60-debugoptimized
- RTX 4090
- 551.52
- Fallout New Vegas - GOG

**Attach files!**
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14365079/d3d9.log)
- [FalloutNV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14365080/FalloutNV_d3d9.log)
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14365081/NvRemixBridge.log)
- [rtx.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14365084/rtx.zip)

**To set up FNV**
1. Download these: 
 - https://github.com/BlueAmulet/RTXRemixStuff/raw/main/NewVegas/NewVegas%20RTX%20Mesh%20Patches.zip
 - https://github.com/BlueAmulet/NewVegasRTXHelper/releases/download/rtx-v0.0.6/NewVegasRTXHelper.zip
 - https://github.com/xNVSE/NVSE/releases/download/6.3.5/nvse_6_3_5b.7z
 - [FalloutNV ini.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14365129/FalloutNV.ini.zip)
2. Extract the contents of nvse_6_3_5b.7z to your game folder
3. Extract the contents of NewVegasRTXHelper.zip to your Data folder
4. Extract FalloutNV ini.zip to your Documents\My Games\FalloutNV folder
5. Install Mod Organizer, set it up for Fallout New Vegas, then install the mesh patch (this isn't strictly necessary)
6. Install RTX Remix, then launch the game from nvse_loader

**To Reproduce**
1. Load the game
2. Observe poor performance
3. If performance is okay, restart the game a few times.

**Expected behavior**
- Performance should be consistently good on such hardware

**Other issues**
- Crashes upon alt-tab on occassion
- Alt-tabbing can decrease performance

**Screenshots**
https://cdn.discordapp.com/attachments/1106553248590090351/1209954240294953083/Fallout_-_New_Vegas_2024.02.21_-_15.04.24.01_edit.mp4?ex=65e8ccb2&is=65d657b2&hm=ecb0b4d264537d41c6116f7669767a8710518372933c3f50f0c552528db3613e&

**Comment by Kim2091** [comment]
This may be down to the patches made to the game to disable culling. A recent patch for Barnyard was made to disable culling as well, and performance noticeably dipped. See the following posts for benchmarks: https://discord.com/channels/1028444667789967381/1106420949257044061/1213016247768195152

FNV and Barnyard have a lot of similarities in terms of Remix bugs due to both utilizing shaders to render terrain. It's possible this is another overlap

**Comment by NV-LL** [comment]
Hello! Will you please test this on the latest release and let us know if the issue persists? Thank you!

**Comment by Kim2091** [comment]
I'll test it tonight. Thank you

**Comment by Kim2091** [comment]
@NV-LL There was a very tiny improvement in performance, but sadly it's still unplayable. I'm not sure if it'll be of here, but here's the Reflex latency information:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/62084776/f1e1c813-d4b4-4d96-9b84-36b62577f08e)

**Comment by NV-LL** [comment]
Thanks for the update! We've filed REMIX-3373 for tracking

**Comment by STHAKKARNV** [comment]
Hi @Kim2091 

I tried with Remix 0.5.4 and vanilla Fallout New Vegas Steam build. I can't reproduce the performance issues even after multiple restarts. I am using a similar Intel 12th gen processor, RTX 4090 and driver version 560.81

Out of curiosity, does this happen for you on a fresh install of New Vegas without any other mods/patches present and driver version 560.81?

**Comment by Kim2091** [comment]
@STHAKKARNV Apologies for the late response. For this performance issue to occur, you need to be using the [anti-culling patch](https://github.com/BlueAmulet/NewVegasRTXHelper) linked in the original post. If you are not using this patch, the performance will be normal.

I speculate the issue is that Remix is being overwhelmed by the significant amount of geometry it needs to process in this scenario.

I have not tested it on 560.81 yet, but I will do so when I have time.

**Comment by NV-LL** [comment]
Hi @Kim2091! I saw that you confirmed #559 was fixed as of yesterday and wanted to see if that also addresses this issue. If not, we'll keep this on the table, but I figured it was worth checking to try to keep our backlog tidy. 😄 Thank you!

**Comment by Kim2091** [comment]
Hi, yes I just tested yesterday, but sadly this isn't fixed yet. In the Reflex statistics, it's attributing the majority of the load to Driver Queue.

Thanks for the follow up :)

**Comment by NV-LL** [comment]
Hey @Kim2091! Can you confirm if perf scales with resolution - i.e., higher at 1080p than 4k? That can help us determine if this is possibly CPU or GPU bounding. Thanks!

**Comment by Kim2091** [comment]
I will check that out tomorrow 🙂

**Comment by Kim2091** [comment]
@NV-LL There are very small gains:
2560x1440: 18 FPS
1920x1080: 18.6 FPS
1280x720: 19.3 FPS

**Comment by nsubtil** [comment]
Those numbers don't look like they're scaling with resolution, which likely means we're CPU bound. Disabling engine-side culling tends to do that, since it typically means the engine has to issue a huge number of draw calls.

Ray-tracing on the GPU scales logarithmically, so GPU time isn't usually a problem, but CPU time scales linearly with draw calls (and Remix has to do a lot more CPU work for draw calls compared to vanilla D3D9).

Without analyzing further it's hard to say for sure, but generally this isn't a problem we can easily deal with on our side. I'd suggest finding another way to make the game work without completely disabling engine-side culling. If there are options to make it less aggressive, that could be a better path forward, together with some of the Remix-side anti-culling features perhaps.

**Comment by Kim2091** [comment]
I appreciate the elaboration. Yes this does appear to be CPU bound. GPU usage is very low.

I did propose to other community members interested in FNV that we implement a custom culling solution, but sadly we're lacking the proper developer for that to happen. Remix's anti-culling doesn't function properly in this game, I think it's dependent on this issue being resolved first: https://github.com/NVIDIAGameWorks/rtx-remix/issues/222

**Comment by MarkEHenderson** [comment]
Hi Kim,

Given the success you've had with Fallout NV recently, is this ticket still relevant?

If there is still a significant CPU bottlenec (and presuming I understand correctly that you're leveraging the API), you might be able to leverage pointInstancing over the API to reduce the overhead when there are many copies of a mesh being rendered (for things like grass, rocks, etc).  see `remixapi_InstanceInfoGpuInstancingEXT`

**Comment by Kim2091** [comment]
@MarkEHenderson This isn't using the API, but I greatly appreciate the advice as I can apply that to my Fallout 4 project which does use it! 

When we last spoke about this project, FNV was still running on a shader based pipeline, just wish some hacks to make it more compatible. Since then, I converted the game to a FFP pipeline using a custom proxy. It does perform better overall now. However, when culling is disabled in the game, performance drops down to the figures we saw before. It runs at around 15 FPS when culling is disabled. The vanilla game runs at a solid 60 in comparison with the patch, so this is an issue on Remix's side.

**Comment by MarkEHenderson** [comment]
Do you have an idea of how many draw calls FNV is sending when culling is disabled?  Right now Remix has a CPU bottleneck when that number is above a couple thousand, but we're working on improving performance there.

(You can get a rough idea by turning on the dxvk hud and looking at the number of instances drawn)

**Comment by Kim2091** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/2163f7b0-ebd0-4d51-9a8a-14a883a3e0b9" />

Seems to be around 1750 instances

**Comment by MarkEHenderson** [comment]
That's actually a surprisingly poor frame time for 1903 total presents.  

Are you familiar with Tracy profiling?  Presuming this is CPU bound, I'd be interested to know where the frame is spending it's time.

**Comment by Kim2091** [comment]
I'll have to learn it, but when I get results I'll post them here :)

**Comment by Kim2091** [comment]
@MarkEHenderson I got a Tracy capture. I've attached it here: https://drive.google.com/file/d/1JFFSjfjoZFotXjs8lwWVWT3IY5778fkg/view?usp=sharing

<img width="962" height="836" alt="Image" src="https://github.com/user-attachments/assets/d2a2e3c3-44d6-4112-8815-1799fa3b1ffb" />

<img width="964" height="834" alt="Image" src="https://github.com/user-attachments/assets/85bc2a0e-3a58-45d0-bdde-e2f0f9360ca6" />

<img width="1647" height="985" alt="Image" src="https://github.com/user-attachments/assets/75ce99b8-8ac2-43d1-be1f-426760df7d23" />

**Comment by MarkEHenderson** [comment]
Hi Kim,

A word of advice - when using the statistics page, you'll want to make sure to limit it to only looking at the frames where actual rendering is happening.  The easiest way to do that is to left click + drag in the top frame bar to highlight a region, then click the 'limit range' checkbox, then click 'limits', and pick 'limit to view'.  Doing that gives a statistics view like this:

<img width="746" height="573" alt="Image" src="https://github.com/user-attachments/assets/e569a16c-4dae-494f-81ec-bee2fdd0b50e" />


When I zoom into a particular frame and compare it to a recent Trace of a well performing scene in HL2, I can see some pretty clear differences.

Yours:
<img width="1176" height="175" alt="Image" src="https://github.com/user-attachments/assets/b145f7d9-3d93-43fb-a642-dbf42477e84a" />
HL2:
<img width="1173" height="147" alt="Image" src="https://github.com/user-attachments/assets/4e0e495a-c1c5-4cf2-8a3c-2c1ad5294984" />

I don't think I've ever seen a pattern where `commitGraphicsState` is called in between every `commitGeometryToRT`, and it seems that those `commitGraphicsState` calls are taking up 5x the time of `commitGeometryToRT`.  It looks like those are all updating shader resources... which I doubt Remix is actually using.  If you can figure out a way to prevent FNV from calling those (or just disable that function on the Remix side) you may get some good results.  If those are actually used, maybe they don't need to be re-set for every draw call?


I also see a lot of very slow calls to `performSkinning`... I'm not sure entirely why, but it looks like a lot of skinning is being done on the CPU instead of the GPU.  You might try changingrtx_geometry_utils.cpp's `const uint32_t kNumVerticesToProcessOnCPU = 256;` to a lower number (like 64) and see if you get a perf boost out of it.  It probably makes sense to just make that constant an RtxOption and add it to the menu, so you can easily raise and lower it to see how that impacts perf.

`InjectRTX` is also taking a lot of time, but that's generally going to be true when the scene is very complex - and proportionately it's take a lot less time than the per-draw-call processing that makes up the first chunk of each frame.

**Comment by NV-LL** [comment]
Hey @Kim2091! Just checking in to see if we should keep this ticket open following Mark's suggestion in the last comment about preventing FNV from calling `commitGraphicsState` so often. Please let us know when you have a chance to try it out, and if it helps at all. Thanks!

**Comment by Kim2091** [comment]
@NV-LL It should stay open 🙂 

I did implement some of Mark's suggestions and saw notable performance improvements thankfully, but there's still more to go and I did find some other stuff I need to write up. I'm currently in the middle of moving so development is slow.
