### ISSUE TITLE
[Runtime Bug]: Game no longer starts with recent versions of Bridge (Painkiller)

### ISSUE THREAD

**Issue by DimplyPickle** [NVIDIAGameWorks/rtx-remix#704]
**(Note this is on an old version of the runtime, please see latest comments for behaviour on newer runtime)**
### Describe the bug

A bug happened where...
Upon attempting to launch the game, one of a few different behaviours occur:
 - The game does nothing but appears in the task manager along with bridge, which is using a large amount of cpu resources
 - A grey/blueish screen appears and nothing occurs, clicking brings up the windows end program or wait dialog
 - A grey/blueish screen appears and shortly afterwards the RTX Remix Runtime Error windows appears, clicking OK closes the game.
 - The game starts up with the loading enhanced assets notice on the bottom left, but crashes shortly afterwards with the RTX Remix Runtime Error
 - The game starts up normally and you can play.

### How do you reproduce the bug?

1) Install Painkiller Black Edition from Steam or GoG.

 OPTIONAL: Install this mod: https://www.moddb.com/mods/painkiller-rtx-remix ("Lite" version is likely sufficient for testing)

2) Attempt to start the game with the latest versions of dxvk-remix and brige-remix

### What is the expected behavior?

The runtime should... 
Launch the game without crashes

### Version

dxvk-remix-0f57dbb-699-debugoptimized, bridge-remix-7c58986-118-debugoptimized

### Logs

[bridge32.log](https://github.com/user-attachments/files/18464089/bridge32.log)
[bridge64.log](https://github.com/user-attachments/files/18464090/bridge64.log)
[remix-dxvk.log](https://github.com/user-attachments/files/18464091/remix-dxvk.log)

**Comment by DimplyPickle** [comment]
Update:

It seems that using the dev release version of dxvk-remix, and the dev debug optimised version of remix-bridge allows us to consistently get into the game, however an error message pops up which we need to press ignore on when we load the game and twice when we load a level. It does work rather consistently like this though.

https://www.moddb.com/mods/painkiller-rtx-remix/downloads/painkiller-rtx-remix-hotfix-v0071-to-0072

**Comment by DimplyPickle** [comment]
Also, if it would be useful to get "real time" additional information, please feel free to message me on the RTX Remix discord: https://discord.com/channels/1028444667789967381/1313627595815911448

**Comment by NV-LL** [comment]
Thanks for reaching out! We've filed REMIX-3876 for internal tracking.

**Comment by DimplyPickle** [comment]
I have tried with the latest nvidia driver and the most recent build of the runtime, and it is impossible to load the game.
Please find logs attached:

[bridge32.log](https://github.com/user-attachments/files/19102219/bridge32.log)
[bridge64.log](https://github.com/user-attachments/files/19102218/bridge64.log)
[remix-dxvk.log](https://github.com/user-attachments/files/19102220/remix-dxvk.log)

**Comment by DimplyPickle** [comment]
using
dxvk-remix-7f622bc-727-release
bridge-remix-7c58986-118-debugoptimized

we are able to load in after pressing ignore on the error that pops up. 
Any bridge after 118 doesn't work

**Comment by DimplyPickle** [comment]
Update: using:

dxvk-remix-7f622bc-727-release
bridge-remix-7c58986-118-release
Also seems to work, with some instability on startup.

Any bridge after 118 doesn't seem to work at the moment.

**Comment by lvengesanam** [comment]
Thanks @DimplyPickle for updating the bug.

I am facing some system issues playing the game.

[bridge-remix-test-2.zip](https://github.com/user-attachments/files/19170932/bridge-remix-test-2.zip)
[bridge-remix-test-1.zip](https://github.com/user-attachments/files/19170931/bridge-remix-test-1.zip)

Could you please try testing with attached bridge-remix binaries along with latest dxvk-remix binaries and update the bug with logs/ crash dumps if any?

bridge-remix-test-1 is built by reverting certain critical change and with bridge-remix-test-2, I have added additional logs to further isolate the issue.

**Comment by DimplyPickle** [comment]
Testing with dxvk-remix-9d97554-734-debugoptimized

test-1:
Run 1:
 - Assertion "Expression:RemixWndProc == prevWndProc" appears on game launch. Pressing "Ignore", I see a light blue screen for about 5 minutes. There is then a crash. There is no dump file. Here are the logs:

[bridge32.log](https://github.com/user-attachments/files/19173239/bridge32.log)
[bridge64.log](https://github.com/user-attachments/files/19173241/bridge64.log)
[remix-dxvk.log](https://github.com/user-attachments/files/19173240/remix-dxvk.log)

**Comment by DimplyPickle** [comment]
test-2:
Run 1:

- Assertion "Expression:RemixWndProc == prevWndProc" appears on game launch. Pressing "Ignore", I see a light blue screen for about 5 minutes. There is then a crash. There is no dump file. Here are the logs:

[bridge32.log](https://github.com/user-attachments/files/19173347/bridge32.log)
[bridge64.log](https://github.com/user-attachments/files/19173349/bridge64.log)
[remix-dxvk.log](https://github.com/user-attachments/files/19173348/remix-dxvk.log)

**Comment by DimplyPickle** [comment]
test-2:
Run 2:

- Assertion "Expression:RemixWndProc == prevWndProc" appears on game launch. Pressing "Ignore", I see a light blue screen. Clicking on the screen causes windows end program or wait dialog to appear. I press end program. There is no dump file. Here are the logs:

[bridge32.log](https://github.com/user-attachments/files/19173373/bridge32.log)
[bridge64.log](https://github.com/user-attachments/files/19173374/bridge64.log)
[remix-dxvk.log](https://github.com/user-attachments/files/19173372/remix-dxvk.log)

**Comment by DimplyPickle** [comment]
@lvengesanam not sure if this is useful information, figured it can't hurt to add:

When running the game with remix, upon game launch, it appears that this light blue window is fullscreen resolution 640x480, even if the game is configured to use (for example) 1920x1080. My monitor OSD still shows that it is running at my desktop resolution.

When running the game without remix, either this then so quickly changes to the configured resolution that it is inperceptible, or the game does not initialize at 640x480, and then the intro cinematics start to play at 1920x1080. I feel that it is probably that the game is still starting at this 640x480 resolution, but when running without remix it is likely changed to the configured resolution so quickly that I can't tell.

**Comment by DimplyPickle** [comment]
> [@DimplyPickle](https://github.com/DimplyPickle) Thanks for the quick update.
> 
> I think we have further isolated the issue with latest bridge version.
> 
> Also, the difference in resolution is only seen when the game crashes?
> 
> Could you do the same tests with below binaries?
> 
> [bridge-remix-test-3.zip](https://github.com/user-attachments/files/19175431/bridge-remix-test-3.zip) [bridge-remix-test-4.zip](https://github.com/user-attachments/files/19175432/bridge-remix-test-4.zip)

The difference in resolution also occurs with remix when the game does not crash.
I will do the tests and report back :)

**Comment by DimplyPickle** [comment]
bridge-remix-test-3:
Appears to work! The assertion about "Expression:RemixWndProc == prevWndProc" appears, and after clicking "Ignore" on the dialog, the game loads and works as expected with remix.
Logs:

[bridge32.log](https://github.com/user-attachments/files/19175598/bridge32.log)
[bridge64.log](https://github.com/user-attachments/files/19175599/bridge64.log)
[remix-dxvk.log](https://github.com/user-attachments/files/19175597/remix-dxvk.log)

**Comment by DimplyPickle** [comment]
bridge-remix-test-4:
Also appears to work! The assertion about "Expression:RemixWndProc == prevWndProc" appears, and after clicking "Ignore" on the dialog, the game loads and works as expected with remix.
Logs:

[bridge32.log](https://github.com/user-attachments/files/19175659/bridge32.log)
[bridge64.log](https://github.com/user-attachments/files/19175657/bridge64.log)
[remix-dxvk.log](https://github.com/user-attachments/files/19175658/remix-dxvk.log)

**Comment by lvengesanam** [comment]
That is great. 

Will update, once these changes are pushed.

In the mean time, you can use below bridge binary for the fix and also to suppress assertion dialog from popping up.

[bridge-remix-test-5.zip](https://github.com/user-attachments/files/19175672/bridge-remix-test-5.zip)

**Comment by DimplyPickle** [comment]
THANK YOU!
I would be super curious to know about what the issue was and how you figured it out!

**Comment by lvengesanam** [comment]
The issue with latest version was with data queue not being in sync. 

The errors that are reported with version - 5 is something unexpected. Only difference between version 4 and 5 is the suppression of one of the dialog boxes from popping up.

Again there are no crash dumps being generated?

**Comment by DimplyPickle** [comment]
> The issue with latest version was with data queue not being in sync.
> 
> The errors that are reported with version - 5 is something unexpected. Only difference between version 4 and 5 is the suppression of one of the dialog boxes from popping up.
> 
> Again there are no crash dumps being generated?

No, there are no crash dumps being generated, at least not in .trex or in the same directory as the game executable.

**Comment by DimplyPickle** [comment]
> The errors that are reported with version - 5 is something unexpected. Only difference between version 4 and 5 is the suppression of one of the dialog boxes from popping up.

On all versions which showed the assertion about "Expression:RemixWndProc == prevWndProc"
(ie test 1, 2, 3, 4)
This same assertion dialog would also appear twice upon level load.
Sorry, I should have mentioned that earlier.

**Comment by lvengesanam** [comment]
Got it. With the latest fix the issue with latest bridge binary is resolved right?
The bugs currently seen existed previously too?

Fix is pushed - https://github.com/NVIDIAGameWorks/bridge-remix/commit/e8b8fd3c1e88befc75588bd70c4e81469eed6854.

**Comment by DimplyPickle** [comment]
> Got it. With the latest fix the issue with latest bridge binary is resolved right? The bugs currently seen existed previously too?
> 
> Fix is pushed - [NVIDIAGameWorks/bridge-remix@e8b8fd3](https://github.com/NVIDIAGameWorks/bridge-remix/commit/e8b8fd3c1e88befc75588bd70c4e81469eed6854).

Hey that seems to work!

The other bugs currently seen with instability and so forth did indeed exist previously.

I do still get the "Expression:RemixWndProc == prevWndProc" assertion if I use the debug build. This does not occur on the release build :)

Thank you kindly!

**Comment by lvengesanam** [comment]
Great! 

Thanks for all the help with testing.

Can you close this bug and create a new bug for other issues you are facing?
