### ISSUE TITLE
[Runtime Bug]: Dawn of War Definitive Edition - Crashes on loading for Remix 0.6.0 and higher

### ISSUE THREAD

**Issue by Llamarider** [NVIDIAGameWorks/rtx-remix#897]
### Describe the bug

Game crashes at different points depending on the remix version - 
0.6.0 - crash after pressing start mission button
1.0.0+ - crash after the first loading screen
In 0.6.0 it still actually renders 3d in the main menu.
Last working version I checked was 0.5.4

### How do you reproduce the bug?

1. Install the game from steam https://store.steampowered.com/app/3556750/Warhammer_40000_Dawn_of_War__Definitive_Edition/
2. Install remix runtime 0.6.0 or 1.1.0 - copy contents of .trex directly to the games directory
3. Launch the game
   3.1. - For 0.6.0 skip intro cutscenes (esc)> go to skirmish>any mission and faction>start game>start mission>crash
   3.2 - For 1.0.0+  skip intro cutscenes (esc)>loading screen> error "Unable to create the error report. Please verify that there is enough space in your TEMP folder."> crash

### What is the expected behavior?

Game doesn't crash and allow you to play any mission or even be in the main menu.

### Version

1.1.0

### Logs

[060_W40k_d3d9.log](https://github.com/user-attachments/files/21934523/060_W40k_d3d9.log)
[110remix-dxvk.log](https://github.com/user-attachments/files/21934524/110remix-dxvk.log)
[054_W40k_d3d9.log](https://github.com/user-attachments/files/21934522/054_W40k_d3d9.log)

**Comment by Llamarider** [comment]
Fixed loading crash on 1.0.0+ by updating drivers

**Comment by NV-DM** [comment]
@Llamarider Could you please confirm the issue is fixed on 1.0?

**Comment by Llamarider** [comment]
I'm still getting it but only after I work with Remix for some time. PC restart helps.

**Comment by Llamarider** [comment]
I also noticed that once the game crashes with the error message "Unable to create the error report. Please verify that there is enough space in your TEMP folder" it won't run again until I restart my pc. Could there be something building up when the game runs?

**Comment by NV-LL** [comment]
@Llamarider are you getting any .DMP files in the folder alongside the game .exe? Not all crashes produce a .DMP file, but it's the most helpful output for us if one does exist. Thanks!

**Comment by NV-LL** [comment]
Hey @Llamarider - checking in again to see if you have any .DMP files (in the folder alongside the game's .exe) that you can provide us. Also, does this crash repro on the latest Remix release, 1.2.4? We'd also like to inform you of our stale ticket policy, specifically that this ticket will be closed as 'went stale' if it does not receive a response in the next 2 weeks. Thanks!
